///<reference types="Cypress" />

it('replanishmentOf Ukrain mobile phone number', () => {
    cy.visit('https://next.privat24.ua/mobile/?lang=en')
        .get('[data-qa-node="phone-number"]')
        .type('939034410')
        .get('[data-qa-node="amount"]')
        .type('350')
        .get('[data-qa-node="numberdebitSource"]')
        .type('5309233034765085')
        .get('[data-qa-node="expiredebitSource"]')
        .type('0124')
        .get('[data-qa-node="cvvdebitSource"]')
        .type('891')
        .wait(3000)
        .get('[data-qa-node="firstNamedebitSource"]')
        .type('Passs')
        .get('[data-qa-node="lastNamedebitSource"]')
        .type('nsnndn')
        .get('[data-qa-node="submit"]')
        .click()
        .wait(3000)
        .get('[data-qa-node="card"]')
        .should('have.text', '5309 **** **** 5085')
        .get('[data-qa-node="amount"]')
        .should('have.text', '350')
        .get('[data-qa-node="currency"]')
        .eq(0)
        .should('contain.text', 'UAH')
        .get('[data-qa-node="commission"]')
        .eq('1')
        .should('have.text', '4')
        .get('[data-qa-node="commission-currency"]')
        .should('contain.text', 'UAH')
       
})
//
it.only('Money tramsfer between foreign cards', () => {
    cy.visit('https://next.privat24.ua/money-transfer/card/?lang=en')
        .get('[data-qa-node="numberdebitSource"]')
        .type('5309233034765085')
        .get('[data-qa-node="expiredebitSource"]')
        .type('0124')
        .get('[data-qa-node="cvvdebitSource"]')
        .type('891')
        .wait(3000)
        .get('[data-qa-node="firstNamedebitSource"]')
        .type('Passs')
        .get('[data-qa-node="lastNamedebitSource"]')
        .type('nsnndn')
        .get('[data-qa-node="numberreceiver"]')
        .type('2222333344445555')
        .get('[data-qa-node="amount"]')
        .type('333')
        .get('[data-qa-node="currency"]')
        .should('contain.text', 'UAH')
        .get('[data-qa-node="toggle-comment"]')
        .click()
        .get('[data-qa-node="comment"]')
        .type('bndfbfbf')
        .get(".amount")
        .find("span")
        .should("have.text", "1")
        //.get('[data-qa-node="submit"]')
       // .click()
       
})


